cli/cli

context/remote.go, context/remote_test.go
Otherwise, the remote URL translation mechanism had crashed when encountering a non-Github.com git remote.
=> Fix parsing non-GitHub remotes

auth/oauth.go, pkg/browser/browser.go, pkg/browser/browser_test.go, utils/utils.go
This ensures that title & body are correctly passed to the browser via URL query parameters.
We had [already fixed this](https://github.com/cli/cli/commit/295c5d122b973de8dffdb096ae93191ac9b52702) for the OAuth flow in the past, but the rest of the codebase used different code for opening the browser. Now they are all unified and correctly tested.
Fixes https://github.com/cli/cli/issues/270
=> Fix `pr create` preview in browser flow for Windows

.github/workflows/go.yml, command/completion.go, command/completion_test.go, internal/cobrafish/completion.go
Fish is now the default shell on macOS, so it's only fitting that we have completion support for it.
Adopting code from https://github.com/spf13/cobra/pull/754
TODO:
=> Add fish completion support

command/root.go, command/root_test.go
Previously, the version string didn't match the `vX.Y.Z` pattern because the wrong variable was passed to `changelogURL`.
Followup to #264, ref. #270
=> Fix `gh version` printing the correct changelog link

_config.yml, _includes/foot.html, _includes/marketing-nav.html, _sass/landing.scss, assets/js/downloader.js, assets/js/terminal.js, assets/js/user-select-contain.js, index.html
* Fixes typing animation
* Makes animated terminal section easier to understand & maintain
* Remove jQuery since it's no longer needed
* Dynamically generate repo & download URLs instead of hardcoding them
* Remove “Sign in, Sign up” links from navigation bar
* Make it easier for user to ~copy~ <ins>select</ins> `brew install` instructions by triple-clicking them on macOS
=> Landing page fixes

.goreleaser.yml, README.md
This PR, along with the new repo https://github.com/cli/scoop-gh , enables `gh` to be installable
and update-able via [scoop](https://scoop.sh).
Closes #280
I also took the opportunity to explicitly say how to upgrade gh in the readme.
=> scoop config for gh

.goreleaser.yml
gh.rb is being written to the root of the homebrew tap where it used to be in the Formula directory;
this PR configures goreleaser to use the Formula directory again.
Closes #299
=> put homebrew formula back in the right place

Makefile, cmd/gen-docs/main.go
- Man pages are now placed under `/manual/`
- Use Jekyll `permalink` to avoid the `.html` extension
- Strip "SEE ALSO" and everything after it
Works in tandem with https://github.com/cli/cli/pull/236
=> Update `make site-docs` to reflect latest setup

command/pr.go, command/pr_checkout.go, command/pr_checkout_test.go
This PR changes the behavior of `gh pr checkout` to _always_ prefix local branch names with
`pr/<id>/<branch name>`. This prevents branch name collisions locally, which currently result in an
ugly git error.
I also took the opportunity to split `prCheckout` into its own file. I have liked having `prCreate` split out like that and given how long `pr.go` has become it seemed like a good idea to split some more.
Closes #233
=> Prefix branch names when checking out a PR locally

.goreleaser.yml
this pr avoids us publishing prereleases to scoop
=> use new goreleaser config

command/pr.go, command/pr_test.go
Tiny thing, but kept bugging me that the checks statuses were capitalized but approval statuses weren't!
=> Make approval statuses sentence case

README.md
Previously referenced one is a duplicate and not conforming to AUR naming guidelines.
See comments: https://aur.archlinux.org/packages/gh/
=> Change AUR package

api/fake_http.go, command/issue.go, command/issue_test.go, command/pr.go, command/pr_create.go, command/pr_create_test.go, command/pr_test.go, command/root.go, command/testing.go, context/context.go, context/remote_test.go
This PR:
- ~uses the wrapper in `pr checkout`~ i'm going to leave this alone for now since it has slightly different behavior
closes #251 
I unscientifically benchmarked the before/after of doing this check. The time hit averaged about .2 sec on my machine/wifi. subjectively it was imperceptible and I don't think caching is urgent.
Originally based on #348
=> More nuanced handling of parent/fork in various commands

git/remote.go
afaik this should be finalURL (the fork) and not initURL (the upstream),
otherwise a bit of the code above can be removed.
=> Fix wrong repo url being used for pushing

README.md
We've gotten a bunch of issues relating to GitHub Enterprise Server (GHES) support, which isn't currently available in `gh`, despite the existence of #273. This is an attempt to clarify that repos not hosted on GitHub.com will not currently work with `gh`.
I'm not wedded to this route of doing it and there may be an opportunity to clarify in the product itself to help avoid confusion, so open to thoughts from others.
=> Add availability section to README

pkg/surveyext/editor.go
Quoting @d0liver [here](https://github.com/cli/cli/commit/ff2d5fa6d07c533e2575cf06f95501fbb24ef254#commitcomment-37262667)
> Looking at this because I had an issue that ended up being unrelated, but I wonder if `else if`s aren't what was intended with the editor check here? Otherwise you'll end up overwriting the value with later checks in cases where multiple env variables are set.
=> Make sure editor is set properly & not overridden later

command/issue.go, command/issue_test.go, command/pr.go, command/pr_test.go, test/fixtures/prView_EmptyBody.json
closes #403
The commit added an empty body check for both issues and PR for preview.
The code ignores the body and the formatting around it if body is empty
```
> ./bin/gh pr view -p 2 -R arkentos/tableturner
This is a test PR with empty body
arkentos wants to merge 1 commit into master from README
View this pull request on GitHub: https://github.com/arkentos/tableturner/pull/2
```
```
./bin/gh issue view -p 1 -R arkentos/tableturner
This is a test issue with empty body
opened by arkentos. 0 comments.
View this issue on GitHub: https://github.com/arkentos/tableturner/issues/1
```
=> Fix: Nil pointer dereference while previewing PR and Issues with empty body

command/pr_create.go, command/pr_create_test.go
Closes #354 
Currently we improperly specify the head ref when submitting a PR cross-repo. This PR fixes that.
Preview in browser and `-w` were and continue to be fine.
Most of the diff is testing.
=> Cross repo pr create

command/pr_checkout.go, command/pr_checkout_test.go
I opened this to address #233 . I was naive in my thinking about how `git push` would subsequently
work and assumed it was easy to convince git to push to differently-named branches. while possible,
it requires more manual user intervention than i'd like.
This PR reverts my branch name prefixing, restoring `pr checkout` to how it was prior. I'll reopen
the original issue and take the approach Mislav originally suggested of only prefixing when it's
actually necessary and warning the user that such prefixing took place.
=> revert pr checkout branch prefixing

auth/oauth.go
Hi!
I noticed that you use `Sprintf` to return a hex string. But it is slower because it has to parse the format string first. This patch brings `EncodeToString` from `encoding/hex` package to improve `randomString` function.
=> Improve randomString function

Makefile
It's bad form to embed timestamps in binaries as it prevents
reproducible builds of the resulting binary.
The Reproducible Builds project defines SOURCE_DATE_EPOCH to help
reproduce binaries by allowing the date format to be overridden. This
patch adds support for this for GNU and BSD date.
Go 1.13 introduces `-trimpath` which strips build paths from all
compiled binaries. This enables people to reproduce the distributed cli
binary without having to recreate the build path.
https://reproducible-builds.org/specs/source-date-epoch/
https://reproducible-builds.org/docs/build-path/
Signed-off-by: Morten Linderud <morten@linderud.pw>
=> [Makefile] Support reproducible builds

command/root.go
Since the Go toolchain is able to extract the module version at build
time, we should use that as a default instead of DEV. This means
customers installing via go-get will get the correct version.
Unfortunately, the toolchain does not store when the build occurs, so
BuildTime now defaults to the empty string. It is still set if build
officially, just not for go-get.
=> command: default to toolchain version

.github/workflows/releases.yml, .goreleaser.yml, context/config_setup.go
It is trivial to extract this information from the released artefacts,
thus there is no security benefit to the safe/development credentials.
This approach also prevents users from using go-get to install.
As proof of concept, and to enable go-get, this change embeds
the GitHub CLI credentials, instead of GitHub CLI (dev).
=> context: use the real oauth credentials

utils/table_printer.go, utils/table_printer_test.go
If the available column width is smaller than 3, don't try to truncate with ellipsis (`...`). Instead, just truncate to available width.
Fixes #431
=> Fix crash in `issue/pr list` for narrow terminals

command/title_body_survey.go
This pr fixes [388](https://github.com/cli/cli/issues/388).
Survey editor returns an empty string if we skip the prompt [editor.go:98](https://github.com/cli/cli/blob/4a5135d820e27a10ec7739d680476e7f95aea54f/pkg/surveyext/editor.go#L98). In this Pr we explicitly set the body equal to template if body is empty and the template content is available.
=> Explicitly replace empty body with default template

command/issue.go, command/pr.go, command/pr_test.go
Since we currently offer no way of querying PRs by combining multiple states with an OR, the best way to handle the `closed` state is to match what the web UI is doing; that is to include merged PRs.
Fixes #475
=> Include merged PRs with `list --state=closed`

command/issue.go, command/pr.go, go.mod, go.sum, pkg/text/truncate.go, pkg/text/truncate_test.go, utils/table_printer.go
Some, if not most characters of some Eastern Asian languages render at double width of a single monospaced Latin character. This compensates for those characters when doing table layout alignment and text trunction:
- Ensure that text is never truncated mid-character, which would result in garbled text
- Ensure that columns in `issue/pr list` output align properly
Tested using Chinese, Japanese, and Korean.
Fixes #279, fixes #515, fixes #516
=> Fix column alignment and truncation for Eastern Asian languages

api/client.go, cmd/gh/main.go, command/root.go, go.mod, go.sum, utils/color.go, utils/table_printer.go
Hi, a few days ago I released this package called [httpretty](https://github.com/henvic/httpretty) that I think would be useful for debugging the GitHub CLI instead of the burden of dealing with it directly.
[![asciicast](https://asciinema.org/a/297429.svg)](https://asciinema.org/a/297429)
What do you think about it? If you like the idea, I probably need to add support for skipping content so that the inspectableMIMEType can still be used.
btw, I was the main maintainer of [NodeGH](http://nodegh.io) for a while (written using NodeJS years ago) but I've since moved to Go (and spent a quite a while working with Go + cobra + git for [deployments](https://asciinema.org/a/192043)), and I'm really excited seeing this CLI written in Go o/ :)
Feel free to ask anything!
=> impr(verbose): using package httpretty to log requests on DEBUG.

api/queries_issue.go, api/queries_issue_test.go
This mimics the `pr list` implementation where any `--limit` value larger than 100 triggers API pagination. Subsequent pages are fetched until the `--limit` value has been reached or until there are no more records.
Followup to https://github.com/cli/cli/pull/540
=> Support `issue list --limit=N` where N is greater than 100

command/repo.go, command/repo_test.go
Example usage:
- `gh repo clone OWNER/REPO`
- `gh repo clone OWNER/REPO -- -o upstream --depth 1`
- `gh repo clone https://github.com/OWNER/REPO.git`
- `gh repo clone git@github.com:OWNER/REPO.git`
Discuss:
- Should we make the `OWNER/` portion optional? In that case, what do we default to? https://github.com/cli/cli/issues/333#issuecomment-590566300
- Should we accept optional 2nd argument as directory destination like `git clone` does?
- There is currenly zero benefit for the user passing the full clone URL to `gh repo clone` over doing it with plain `git clone`. Should we still support the URL argument?
- Currently the shorthand `OWNER/REPO` expands to an HTTPS clone URL. How do we acommodate people who would prefer SSH clone URLs by default?
Fixes #333
=> Add `repo clone <repo>` command

api/queries_pr.go, command/pr.go
Closes #212 
I like @ampinsk's idea, let me know if you need anything changed!
Screenshots:
=> Use gray color for PR number if PR is a draft

auth/oauth.go
Mitigates https://github.com/cli/cli/issues/297
This adds some more information to the output when authentication fails
due to `gh` being unable to open a browser. It communicates the details
of the workaround without the user having to search issues on the `gh`
repo to see how to get around it.
I also added some empty lines as the output is kind of hard to parse at present.
=> Print details of authentication workaround to terminal

.gitignore, api/queries_pr.go, api/queries_repo.go, command/issue.go, command/pr_checkout.go, command/root.go, command/title_body_survey.go, context/blank_context.go, context/context.go, git/ssh_config.go, internal/cobrafish/completion.go, internal/ghrepo/repo.go, update/update.go, utils/table_printer.go
It's micro optimization which in this project doesn't make sense.
I just prefer it, maybe it's just my personal opinion, so I get it if it will be rejected.
When empty struct needs to be created, I prefer
```go
var myStruct MyStruct
```
vs
```go
myStruct := MyStruct{}
```
And when we're doing "map" from some object to another in slice, we can specify capacity in advance to avoid multiple reallocations.
```go
results := make([]Result, 0, len(in))
for _, obj := range in {
results = append(results, obj.toResult())
}
```
vs
```go
results := []Result{}
for _, obj := range in {
results = append(results, obj.toResult())
}
```
When slice could be empty, we can just declare it
```go
var results []Result
```
vs
```go
results := []Result{}
```
this
```go
t.rows = [][]tableField{[]tableField{}}	
``` …
=> Slice initialization

command/issue.go, command/issue_test.go, command/pr.go, command/pr_test.go
Previously, entering a PR or Issue number as listed and as displayed on GitHub web site (with a leading "#") would fail. Bash and some other shells treat "#" as a comment, so the only way to actually enter a #<num> is by escaping or quoting it in any case.
Now, if the user managed to get a PR or issue number with a leading "#" past their shell and into the program, it will be treated the same as a plain number.
Additionally, some help text is added to point out the problem of "#" marking the start of a comment
Fixes #315
=> Handle properly passed #<num> as equivalent to <num> for PRs and Issues

command/issue.go
As a followup of #474, there's an opportunity to improve the error message for when there are no arguments (or we don't think there are no arguments as in the case if someone uses a #). This just adds a bit more to the error message to specify that it should use either the issue number or the URL as an argument.
=> Improve error message for issue URL with no args

api/queries_pr.go, command/pr.go
Fixes #467
I took a look at #467 and figured out a way to print a PR state of the current branch.
I simply added the state at the end of the line for now.
```
$ gh pr status
Relevant pull requests in doi-t/cli-test
Current branch
#1  Test 467 [test467] (MERGED)
Created by you
#2  Test 2 [test-2]
Requesting a code review from you
You have no pull requests to review
```
```
$ gh pr status
Relevant pull requests in doi-t/cli-test
Current branch
#2  Test 2 [test-2] (OPEN)
Created by you
#2  Test 2 [test-2]
Requesting a code review from you
You have no pull requests to review
```
```
$ gh pr status
Relevant pull requests in doi-t/cli-test
Current branch
#3  Test 3 [test-3] (CLOSED)
Created by you
#2  Test 2 [test-2]
Requesting a code review from you
You have no pull requests to review
``` …
=> Ability to differentiate pull requests by their state

command/root.go
This compensates for what appears to be a bug in Cobra, which only handles `pflag.ErrHelp` unless the error is wrapped. It also might be that Cobra doesn't recognize Go 1.13-style error wrapping.
Closes #565
=> Ensure that `gh <command> -h` is equivalent to `--help`

api/fake_http.go, command/pr.go, command/pr_test.go, test/fixtures/prStatusFork.json
Now passing base repo as reference to `prSelectorForCurrentBranch()` so that it doesn't have to (inexactly) determine the base repo itself and risk it being different than the base repo determined during `pr status/view` main command logic.
Fixes #561, closes #566
=> Fix detecting PR for current branch pushed to fork

.github/workflows/releases.yml
closes #569
adds a workflow step for releasing that moves anything from the Pending Release column over to the
Done column.
I, uh, tested it on a local Ubuntu machine but haven't actually tested it in prod. I figure I'll
debug it if needed during the next release.
There might be a better way to skip for prerelease but I think what I have works.
=> Move pending release cards into done on release

README.md
We just shipped repo commands but they're not present in our README, so this adds that.
=> Add usage to README for repos

command/repo.go
In all the short usage descriptions we don't use periods at the end except in these two. So this updates them to match the others.
=> Consistent punctuation in repo usage

api/fake_http.go, context/context.go
I ran a [typo checker](https://github.com/marketplace/typo-ci) over the codebase & spotted two spelling mistakes within the code.  
This PR corrects them (They were in comments, so not a big change).
=> Fixing 2 typos

command/root.go
- Draft pull requests (previously under `shadow-cat` preview) are now fully available
- PR `reviewDecision` and `statusCheckRollup` (previously under `pe_mobile` feature flag) are now fully available, although the latter still requires `antiope` preview for the time being
No longer relying on the `pe_mobile` feature flag means that people can now use Personal Access Tokens with GitHub CLI https://github.com/cli/cli/issues/297#issuecomment-587708363 https://github.com/cli/cli/issues/273#issuecomment-587703737
=> Stop opting into API previews that have since shipped

command/pr_create.go
If there are any errors related to user input, or if the PR create operation has been cancelled via the interactive survey, avoid forking the repo or pushing the branch.
The diff might seem large, but this only swaps the old implemenation around.
Fixes #482, fixes #558, closes #615
=> Ensure `pr create` validates all inputs before forking+pushing

api/queries_repo.go, api/queries_repo_test.go, command/repo.go
We were passing the wrong parameter name.
Fixes #608, followup  to https://github.com/cli/cli/pull/547
=> Fix setting homepage URL in `repo create`

command/completion.go, command/completion_test.go
This also un-hides the `completion` command so it appears in `gh help` and is thus more discoverable.
=> Add support for PowerShell completion

command/repo.go, command/repo_test.go
To block or ignore the invalid/ fake repo URL from opening the browser while running,
`gh repo view [repo_url]`
Fixes #598
=> Verify repository before viewing in the browser #598

api/queries_issue.go, api/queries_issue_test.go, command/issue.go, command/issue_test.go, test/fixtures/issueList.json
This provides support for filtering issues by author with the `issue list` command.
The flags are `-A` and `--author`. Fixes #389.
Edit: PR support for filtering by author isn't available from the API so that'll need to happen in a follow up PR. I (Billy) updated #389 to just be scoped to issues so this can close that issue when it's merged.
=> Add filter issues by author

README.md
Updated instructions to use `dnf` package manager instead of `yum`, which has been the default package manager in Fedora since Fedora 22 (2015).
=> Update Feodra install instructions

api/queries_pr.go, command/pr.go, command/pr_test.go, test/fixtures/prStatusClosedMerged.json, test/fixtures/prStatusCurrentBranch.json
Closes #621
With this fix, `gh` only shows the most recent PR for the current branch as shown below (`foo` branch has `Merged` and `Closed` PRs in this case). I added a test along with a new test data (`test/fixtures/prStatusCurrentBranch.json`) to verify it.
It shows the most recent PR regardless its status.
(Changes on `test/fixtures/prStatusClosedMerged.json` are only for indentations and PR numbers.)
=> Only show the most recent PR for the current branch

auth/oauth.go
Web developers who have had at any previous point ran an application on `http://localhost` that enabled HSTS (HTTP Strict Transport Security) will find themselves unable to authenticate because their browser (typically Safari) will keep redirecting them to `https://localhost`, which isn't handled by our local server.
This switches the authorization callback to be to `127.0.0.1`, which should be equivalent to `localhost`, but not subject to HSTS.
The GitHub CLI OAuth apps have been edited to add `http://127.0.0.1/callback` as an additional allow-listed callback URL. /cc @ptoomey3
Fixes #616
=> Avoid redirecting to `localhost` during authorization flow

command/issue.go, command/issue_test.go, command/pr_checkout_test.go, command/pr_create.go, command/pr_create_test.go, command/pr_test.go, command/repo_test.go, command/testing.go, command/title_body_survey.go, git/git.go, git/git_test.go, test/helpers.go, utils/utils.go
closes #216
This PR provides defaults for title/body in a PR based on commits.
If 1 commit: PR title is commit message, body is commit body
If >1 commits: PR title is branch, body is listing of commits
Note that in both cases, PR templates supersede the body generation.
This PR also adds two improvements to our test suite:
- `AskStubber`. This can be used to simulate user input to a prompt created by `survey`. You can either specify specific values that a user would input or just have  `survey` use the default. 
- `CmdStubber`. This allows us to set up a number of expected calls to external commands. It's pretty simple for now and is intended to just replace the hacky ExecStubber thing that was there previously and add the ability to stub multiple times (instead of a single call to …
=> autofill title/body for PRs

command/issue.go, command/issue_test.go
Currently, `issue list` and `issue status` have different printing formats.
This PR adds the `age` section for `issue list` and uses the `tablewriter` for `issue status` to keep the format consistency between them.
=> fix: inconsistent format between issue list and status

command/pr_test.go, test/fixtures/prStatusCurrentBranchClosed.json, test/fixtures/prStatusCurrentBranchMerged.json
This PR is a follow-up of #638 
#624 and #638 introduced `Closed` and `Merged` states of the current branch. However, I didn't add tests for each new state. This PR adds unit tests that checks the most recent `Closed` and `Merged` states of the current branch.
There is no core logic changes in this PR.
Since gh command returns [opening "reviewRequested" and "viewerCreated" PRs](https://github.com/doi-t/cli/blob/74a2a241045d9e6df3bbe288f81911b4361871cd/api/queries_pr.go#L232-L233) for `gh pr status`, I removed `TestPRStatus_closedMerged` which had `CLOSED` and `MERGED` PRs for `viewerCreated` in the fixture.
=> Add unit tests for Closed and Merged states of the current branch

command/pr.go
- Allow `pr status -R <repo>` usage from outside of a git repo - fixes #339
- Allow `pr status` use when on detached HEAD - fixes #282
=> Allow `pr status` in cases where there is no current git branch

README.md
This PR adds more detail to the README about why GHES support is coming later.
=> More detail about GHES support

command/repo.go, utils/utils.go
Explicitly assign the writer stream for the progress spinner so that tests may override it.
The default when not in testing stays the same: the output stream is the colorable stdout.
I spotted this by seeing `- Forking OWNER/REPO...` output mixed together with a failure of a test unrelated to `repo fork`.
=> Enable tests to capture spinner output

command/pr.go, command/pr_checkout.go, command/pr_checkout_test.go, command/pr_test.go
Previously, the repository owner+name component of the URL was ignored and only the pull request number was read. Now, the URL dictates which base repository will be used.
As a bonus fix, the global `--repo` argument is now respected for `pr checkout`. https://github.com/cli/cli/pull/633#issuecomment-597825711
Fixes https://github.com/cli/cli/issues/408
=> Respect base repository when passing URL argument to `pr checkout/view`

api/queries_pr.go, command/pr.go, command/pr_create.go, command/pr_create_test.go
closes #686
when checking for existing pull requests for a given branch we weren't taking the base branch into
account, thus preventing -B from being useful once a pull request existed for a given branch.
=> respect -B when checking for existing pull requests

api/queries_repo.go, command/issue_test.go, command/pr_test.go, command/repo.go, command/repo_test.go, test/helpers.go
Changes `repo view` to default to terminal output. Adds `-w`/`--web` to suport previous behavior.
(...snip...)
blank repo:
closes #623
I included only the metadata suggested in #623: full name, description, readme, and url. If a readme is detecting as being not-markdown, it's rendered as plain text. A blank readme is rendered the same as no readme ("No README provided").
I added a helper called `ExpectLines` to our test helpers. I noticed we were copying a pasting a ton
of lines for checking a list of regexes against captured STDOUT and was able to get rid of ~60 lines
from the test suite.
=> Add ability to view repo in terminal and do it by default

api/pull_request_test.go, api/queries_pr.go
The "STALE" conclusion had shipped this January and is basically a conclusion that can only be reported by GitHub and not explicitly set by any integrations.
I could not decide whether to map it to a "success" or a "failure" state, so I chose "pending" instead.
Fixes #705
=> Prevent crash when encountering "STALE" check conclusion

internal/ghrepo/repo.go, internal/ghrepo/repo_test.go
Using `www.github.com` in git remote URLs is certainly not common, but GitHub technically supports it and it's not hard for us to support it too.
Fixes https://github.com/cli/cli/issues/693
Bonus:
- transition `repoFromURL` to table-driven test
- add code docs for `ghrepo` package
=> Support `www.github.com` git remote URLs

command/repo.go, command/repo_test.go
Avoid adding a new git remote for a fork if an existing remote is found that points to the exact forked repo.
Fixes #580
=> repo fork: reuse existing git remote if available

command/pr_checkout.go, command/pr_checkout_test.go, command/pr_create.go, command/pr_create_test.go, git/git.go
A branch is considered already pushed if its HEAD commit hash matches the commit hash of one of the remote tracking branches: `refs/remotes/<remote>/<branch>`
This mechanism allows the user to:
- Choose a remote as push target for their branch different than the one that would automatically get chosen for them by `pr create`;
- Avoid a `git push` operation (and its associated git hooks) if a push was not necessary in the first place.
Drawbacks:
- If an older version of the branch is pushed to a remote, but later some new commits were added to the local branch, the existing remote tracking branch will intentionally _not_ be considered a push target. This conservative approach is to avoid false positives due to:
- One of the remotes having an unrelated branch that just so happens to share …
=> Avoid auto-forking/pushing an already pushed branch in `pr create`

api/queries_repo.go, command/pr_create.go, command/pr_create_test.go, command/repo.go, context/context.go, context/remote_test.go, git/remote.go
Before: the default push target for the current branch in `pr create` was **the first repository found among git remotes that I have write access to**, even if it is the same as the base repository.
Now: the default push target is **the fork of the base repo, if said fork exists** and I have write access to it (even if it's not listed among git remotes), falling back to old behavior otherwise.
This change in the default is to facilitate contributions to projects that have a hard requirement that all pull requests (even those opened by people with write access to the project) always come from forks. If a fork exists, it will automatically get used as a push target.
Fixes https://github.com/cli/cli/issues/350
=> Creating a PR now always prioritizes an existing fork as a push target

command/issue_test.go, command/pr.go, command/pr_checkout.go, command/pr_checkout_test.go, command/pr_create_test.go, command/pr_test.go, command/repo.go, command/repo_test.go, command/testing.go, context/context.go, git/git.go, git/git_test.go, git/remote.go, internal/run/run.go, test/helpers.go, utils/utils.go
closes #682
~This adds a kind of gross hack to enable branch detection on a repo with no commits. You are "on" a
branch; but without commits `rev-parse` fails. `branch` is also not helpful. i noticed that `log`
tells you the branch you are on (that is lacking commits), so I extracted the branch name from the
error.~
This adds a fallback to `symbolic-ref` when doing branch detection so that it works on an empty repository. `symbolic-ref` is defined as far back as git 1.9.
I took this opportunity to touch `utils.Runnable` and `CmdStubber` some more:
- moved the prepare cmd stuff (including the `Runnable` interface) into its own package,
`internal/run`
- added `StubError` to `CmdStubber`. This is primitive in that it's working with a raw `error`
instead of `CmdErr` but I figure it was enough …
=> fix branch detection on empty repo

api/fake_http.go, api/queries_repo.go, command/pr_create.go, command/pr_create_test.go
This is to avoid errors when a local base branch is missing or out of date.
Fixes #710, closes #713
=> Use remote tracking branch for base when detecting commits for `pr create`

api/queries_repo.go, command/repo.go, command/repo_test.go, go.mod, go.sum
When `gh repo clone`-ing a forked repo, the resulting local repo will automatically have an "upstream" git remote added that points to the parent repo of the fork being cloned.
Additionally, this PR introduces usage of the https://github.com/shurcooL/githubv4 library for GraphQL requests. Benefits over our hand-rolled GraphQL approach include:
- Having the GraphQL query string auto-generated from the result struct
- Type-safety for input variables: the `githubv4` library declares a Go type for each scalar type defined in GitHub API v4
Fixes https://github.com/cli/cli/issues/620
=> Automatically set up "upstream" remote for forks

.github/workflows/go.yml
This will help avoid introducing code changes that are not properly formatted, or `go mod` dependency changes that are untidy.
[Example failure output](https://github.com/cli/cli/runs/551915751?check_suite_focus=true)
Ref. 0680bb5c6c230ea6adccbc63c1374fe56d11d971
=> Assert that running `go fmt` or `go mod tidy` produces no changes in CI

api/fake_http.go, command/pr_create.go, command/pr_create_test.go
When an existing `headRepo` couldn't be detected, it's time to auto-fork one. Unfortunately, an obscure Go behavior made it seem like `headRepo` was a non-nil value, where in fact it did contain a nil pointer which would crash the process.
This avoids ever assigning nil pointers to `var headRepo ghrepo.Interface`. https://golang.org/doc/faq#nil_error
Fixes #722
=> Fix auto-forking scenario in `pr create`

command/completion_test.go
I think this was a tiny copy-paste error that might be confusing if the test ever does fail.
=> Clarify error in powershell completion test

README.md
This is linked to from GitHub.com call-to-action to install CLI.
Ref. 53b5c22478fedab746d41b2d62ebc4abef855879
=> Bring back `#installation` anchor in README

.github/workflows/go.yml, .github/workflows/lint.yml, api/queries_issue_test.go, api/queries_repo_test.go, auth/oauth.go, command/issue.go, command/issue_test.go, command/pr_checkout_test.go, command/pr_create_test.go, command/pr_test.go, command/repo_test.go, command/root.go, command/root_test.go, command/testing.go, context/config_setup.go, git/git_test.go, git/ssh_config.go, pkg/githubtemplate/github_template_test.go, pkg/surveyext/editor.go, pkg/text/truncate.go, test/helpers.go, update/update.go, utils/table_printer.go
~~Right now linting failures don't fail the CI job, but they might in the future.~~ They do fail the build now that all previous linting failures were cleaned up.
Also, only run linters on ubuntu (since it doesn't make sense to run them cross-platform) and only when Go files were modified.
=> Check code with golangci-lint on push

utils/color.go, utils/utils.go
I have a hard time reading colorized text in most circumstances. This change adds support for the `NO_COLOR` environment variable. I've tried to conform to the style here so let me know if there's anything I need to adjust.
Love the tool. Thanks for making it. 🖤
=> Support NO_COLOR environment variable to disable color

command/repo.go, command/repo_test.go
Fixes #653 
This allows a user to specify the target directory to clone to as part of the additional arguments.
It's not the prettiest implementation, but it works. It essentially parses the extra args to find any orphaned ones, Ideally we could somehow leverage git's actual command line arg parsing, maybe through something like this. But this is pretty much my first go code, so I wasn't really sure how to go about doing that.
Based on conversation in #721, this functionality was separated into it's own feature.
=> Respect clone target

api/queries_issue.go, api/queries_pr.go, command/issue.go, command/issue_test.go, command/pr.go, command/pr_test.go, go.mod, go.sum, test/fixtures/issueView_preview.json, test/fixtures/issueView_previewClosedState.json, test/fixtures/issueView_previewNoLabel.json, test/fixtures/issueView_previewWithEmptyBody.json, test/fixtures/prStatus.json, test/fixtures/prStatusFork.json, test/fixtures/prView.json, test/fixtures/prViewPreview.json, test/fixtures/prViewPreviewClosedState.json, test/fixtures/prViewPreviewDraftState.json, test/fixtures/prViewPreviewDraftStatebyBranch.json, test/fixtures/prViewPreviewMergedState.json, test/fixtures/prView_EmptyBody.json, utils/utils.go
Closes #652
Mostly tests for each state. Changes for the core logics are a few lines in `command/issue.go`, `command/pr.go` and GraphQL queries.
Since colors matter, I tried to test PR/Issue states with ansi escape sequence to compare colors along with its string but couldn't figure out an efficient way to do... I might be missing something for it.
I use `•` (Bullet: `U+2022`) as a separator. It is a bit ugly in below captures but I think it is my terminal font problem. 💦 
- Open PR
- Draft PR
-  (idea) We could change `Open` to `Draft` like below if it is more appropriate
- Closed PR
- Merged PR
=> Show the state (open, closed, merged) in issue view and pr view

command/repo.go, command/repo_test.go
This is a naive proposal for fixing #731
=> Fetch upstream remote after adding it

command/pr_checkout.go, command/repo.go
changes "PR" ---> "pull request" for consistency and clarity
Also, changes "repo" to "repository"
ready for review
=> spell out PR text

README.md
Addresses #367 , even if it's been discussed and closed.
MacPorts has had 'gh' since Feb 13 (version 0.5.4). I understand the 'gh' developers have chosen "to support Homebrew for macOS officially", and you will not provide support for MacPorts.
We in MacPorts will support our own, as we do already for what we provide. When relevant, we push upstream fixes we have developed or determined appropriate to use -- contributing back to the greater good -- as well as keep projects updated in MacPorts as best our times allows.
This gh change is purely to the top-level ReadMe, noting that gh is available from both Brew and MacPorts, and how to install and update it for both. If you would prefer language that you officially support Brew and not MacPorts, that's your option. But, I don't see anything …
=> add MacPorts usage info

cmd/gh/main.go, command/completion.go
* Improve user-friendliness of `completion` command
When ran directly in the terminal, the command now errors out with:
$ gh completion
error: the value for `--shell` is required
see `gh completion --help` for more information
This is to avoid the previously default bash code output confusing the user if they ran the command out of curiousity.
A backwards compatibility layer is present here: if stdout is not a terminal, then output bash code like before. This is to support users who have already added a line like this to their bash profile:
eval "$(gh completion)"
* Avoid checking for updates during `gh completion`
This is due to the fact that `gh completion` can be programatically used during shell startup and we definitely don't want to:
1. slow down people's startup time;
2. show any …
=> Improve `completion` command

command/issue.go, command/pr.go, command/repo.go
- Short-form docs for `pr/repo view` no longer say "in browser"
- Long-form docs for all these commands now list more information about what will be displayed in the terminal, plus stressing out the alternate behavior with the `--web` flag.
- `--web` flag docs: add English articles
Fixes #763
=> Improve `issue/pr/repo view` documentation

.github/CONTRIBUTING.md
We started out by saying that we don't want PRs for anything except bug fixes. Things have evolved a bit since we announced the beta such that we've gotten some excellent community contributions (thank you! 💖) beyond bug fixes. We still want to acknowledge that our team is very small and we don't have the bandwidth for PRs for everyone's favorite feature request, so we'll still require an issue to be the first place to discuss all but the smallest and most straightforward feature additions. But this PR makes clearer that when we've given the ok 👍 in an issue for a community member to work on something, we'll be happy to merge PRs for features.
=> Update contributing doc to reflect something closer to reality

.github/workflows/go.yml, .github/workflows/lint.yml, .github/workflows/releases.yml
Switch to `actions/setup-go@v2-beta` which advertises better retries around downloading the Go version.
https://github.com/cli/cli/runs/582899858?check_suite_focus=true
=> Avoid intermittent CI failures while setting up Go

README.md
apt can now install local .deb files too, with dependencies.
=> Update Debian instructions for modern apt versions

.github/CONTRIBUTING.md
Clarify that we would prefer to not get contributions adding installation instructions for any OS or package manager that isn't in the few major ones that we've already covered.
Bonus:
- "PR" 👉 "pull request"
- add section about building and testing
=> Tweak CONTRIBUTING docs to clarify our stance about installation instructions

command/title_body_survey.go, pkg/surveyext/editor.go
fixes #308 
gh now respects and prioritizes whatever is set with `gh config set editor ...`. it chooses an editor in this way:
- set in GH_EDITOR?
- explicitly configured via `gh config`?
- set in GIT_EDITOR?
- set in VISUAL?
- set in EDITOR?
- nano (!windows), notepad (windows)
unfortunately adding tests did not make sense as the relevant change is below the level at which we can reasonably test survey code. the surface area is small and i think the risk is low.
=> respect configured editor

command/pr_checkout.go, command/pr_create.go, command/repo.go, command/repo_test.go, command/root.go, command/root_test.go, git/remote.go
Fixes #546
this adds recognition of the `git_protocol` setting when:
- creating a repo
- cloning a repo
- forking a repo
- forking/pushing during pr create
- checking out a PR
additionally, it:
- consolidates remote adding to use AddRemote; this introduces a fetch
where there previously hadn't been one
- changes repo clone to accept an ssh url
- changes repo fork to accept an ssh url
i just added basic unit tests; adding new test cases for all of the
above scenarios seemed like diminishing returns.
=> respect git_protocol setting

command/repo.go, command/repo_test.go
because of some commit reverts i ended up missing a place where we form a remote url ^_^()
=> missed a remote url

.github/workflows/releases.yml, Makefile, docs/releasing.md
Runs `make site-publish` upon every (non-pre)release. This generates man pages, bumps the version number in `index.html` and pushes to the site repo.
=> Update documentation site on release

.github/workflows/releases.yml
This fixes our release process when there is more than one git tag pointing to a commit.
https://github.com/cli/cli/runs/610170624?check_suite_focus=true
https://github.com/goreleaser/goreleaser/pull/1327
=> Help goreleaser find the correct git tag during release

command/root.go
Per code documentation: "BasicClient returns an API client that borrows from but does not depend on user configuration". This means that any errors while reading `oauth_token` should be tolerated.
=> Fix gh updater mechanism for unauthenticated users

api/queries_pr.go, command/pr.go, command/pr_test.go
Relies on #854
Here is what it looks like
This command isn't as straight forward as that though because the PR could be merged. If it is we show the message below.
Closes #413
=> Add `gh pr reopen <numberOrURL>`

api/fake_http.go, command/pr.go, command/pr_test.go
Fixes #805
We should not display closed/merged PRs under the `Current Branch` heading if the current branch is also the default branch - otherwise they will always show up when running `gh pr status` from the default branch
This can occur is someone accidentally gets the branches around the wrong way trying to make a PR and does `master/default -> branch`
=> Hide closed/merged PRs from default branch

command/completion_test.go, command/config_test.go, command/issue_test.go, command/pr_checkout_test.go, command/pr_create_test.go, command/pr_test.go, command/repo_test.go, command/testing.go
In our tests we call RunCommand like this `output, err := RunCommand(issueListCmd, "issue list")`. I was running into a problem where I would call RunCommand with the wrong command! For example, instead of `RunCommand(issueListCmd, "issue list")` I would call `RunCommand(OMGWrongCmd, "issue list")`. This caused lots of problems because stderr and stdout weren't being captured in a way I could see. I was very confused.
Could I have avoided this problem I was more thorough? Yes, but as we all know humans make errors especially if their name is @probablycorey. So I propose we protect our future selves by changing the arguments to `RunCommand` to `func RunCommand(args string) (*cmdOut, error)`. We can use cobra's ability to parse raw strings to figure out which command should be run.
@mislav …
=> RFC: Make `RunCommand` less brittle

command/issue.go
Another possibility is to not prompt the user interactively if `title` is passed. See @mislav [comment](https://github.com/cli/cli/issues/807#issuecomment-616490656) in the issue.
Closes #807
=> Disable interactive mode for `issue create` if all flags are passed

pkg/githubtemplate/github_template.go, pkg/githubtemplate/github_template_test.go
YAML parsing sometimes gets sabotaged by asterisks that follow the end of frontmatter (`---`). We now scope YAML parsing to only frontmatter and we don't pass any contents that follow.
Fixes #832
=> Fix parsing some issue template names

api/queries_pr.go, command/pr_review.go, command/pr_review_test.go, command/testing.go
This PR implements part of the lightweight reviewing (scenario B) designed here: https://docs.google.com/document/d/1lk4C5nqNWuOHxy0CDQKLbbrl6GRm4Y3f3FU4xTXgdhI/edit specifically with using boolean flags + a `--body` string flag
For now it's just the non-interactive component; given that this PR was getting a little long I'm doing the survey case in a follow-up.
examples:
```
gh pr review -a                               # mark the current branch's pull request as approved
gh pr review -c -b "interesting"              # comment on the current branch's pull request
gh pr review 123 -r -b"needs more ascii art"  # request changes on pull request 123
```
Related to #434
=> non-interactive gh pr review

.github/CONTRIBUTING.md, .github/workflows/go.yml, .github/workflows/lint.yml, .github/workflows/releases.yml, docs/source.md
This ensures that we're testing against and compiling binaries for releases using the newest version of Go.
Ref. https://github.com/cli/cli/issues/514
=> Upgrade to Go 1.14 in CI

api/queries_pr.go, command/pr.go, command/pr_test.go, test/fixtures/prStatusCurrentBranch.json, test/fixtures/prStatusCurrentBranchClosed.json, test/fixtures/prStatusCurrentBranchClosedOnDefaultBranch.json, test/fixtures/prStatusCurrentBranchMerged.json, test/fixtures/prStatusCurrentBranchMergedOnDefaultBranch.json
At the time we have a reference to `baseRepo`, we might still not have contacted the API nor obtained any information about the default branch for the repository. This expands the `PullRequests()` query to always report the default branch so we may choose how to render entries that belong on the current branch.
Fixes https://github.com/cli/cli/pull/842#discussion_r420175086 /cc @foad
=> Fix `pr status -R` crash with closed PR on the default branch

docs/command-line-syntax.md
Here is my first pass at some documentation for how we use this. 
**Questions:**
- We don't have good examples for some simple patterns, like mutually exclusive arguments. We have examples, but they are kind of complicated. 
- Do we want to include more examples of things like "a required flag with mutually exclusive placeholder arguments"
References:
[google](https://developers.google.com/style/code-syntax) - pretty thorough, but doesn't follow the standards we've been using
[microsoft](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/command-line-syntax-key) - very simple, but matches what we have
[ibm](https://publib.boulder.ibm.com/tividd/td/tec/SC32-1232-00/en_US/HTML/ecormst15.htm) - like microsoft's but with more examples
=> Add command line syntax doc

command/pr_review.go, command/pr_review_test.go
this pr fixed a small but irritating bug in the `pr review` code. it was in the blindspot for tests
and magnified by my lax switch statement.
=> tyop fix + stricter switch

api/queries_pr.go, command/pr.go, command/pr_test.go
This adds the `gh pr merge` command and it works like this.
`gh pr merge` merges the current PR
`gh pr merge 54` merges PR #54 
It has three mutually exclusive flags `--rebase`, `--merge`, and `--squash`. The default flag is `--merge`
Here is what it looks like:
**What will be in follow up PRs**
1. Making `gh pr merge [number | url]` interactive if there are no flags
2. Investigate how much work it is to follow the merge rules setup for a branch
Part 1 of closing #373
=> Add support for `gh pr merge`

api/queries_pr.go, command/pr_create_test.go
When reviewers were requested on a PR, they would apparently overwrite the current set of reviewers. A fresh PR will already have reviewers if it was assigned some by CODEOWNERS rules.
The fix is to [only ever add additional reviewers](https://developer.github.com/v4/input_object/requestreviewsinput/) and not overwrite the entire set. 
Fixes #910
=> Preserve CODEOWNERS reviewers in `pr create`

api/queries_repo.go, api/queries_repo_test.go, command/issue.go, command/issue_test.go, command/pr_create.go, command/pr_create_test.go, command/title_body_survey.go, pkg/httpmock/stub.go
Command tested:
```
gh pr create -R github/github -t 'title' -b 'body' -a hubot -r github/<team> -l bug
```
Results:
- before: **18.420s** spent in metadata resolve
- after: **0.411s** spent in resolve
This is achieved by avoiding preloading all org users and teams (as it would if assignees or reviewers were requested in interactive mode) and manually assembling a query that resolves an assortment of GraphQL nodes to IDs in bulk.
Followup to https://github.com/cli/cli/pull/787
=> Faster resolve assignees, reviewers, labels on create via flags

command/repo.go
I suggest using simple information on help command like (default: private) that it can be clean for users to understand that the repository will be created as private.
Fixes #890
=> add description default private for repo create

docs/source.md
Changing one's PATH is platform- and shell-specific and I would like us to avoid including those instructions in our documentation. Instead, this suggests to move the binary into a place already on the PATH.
Fixes #922
=> Change source installation docs to avoid suggesting to change PATH

api/queries_issue_test.go, api/queries_repo_test.go, command/repo.go, command/root.go, context/blank_context.go, context/context.go, internal/ghrepo/repo.go
As per https://github.com/cli/cli/issues/882, here's the associated PR. It ended up requiring a little more refactoring than I initially anticipated 😄That said I ended up mirroring the behavior of `FromUrl` (https://github.com/cli/cli/blob/master/internal/ghrepo/repo.go#L42) given it's functionally similar. All current tests pass (and figured no new ones needed). Any queries, just let me know 👍
=> Improved error message when "owner/repo" format not provided

command/issue.go, command/pr.go, command/pr_checkout.go, command/pr_review.go, command/repo.go, command/root.go
Fixes #914
It is Mislav's and my hypothesis that the failed reauth issue was caused by having multiple
`apiClient` instances during a command's lifetime. The second `apiClient`s are created inside of
`determineBaseRepo`; this PR changes `determineBaseRepo` to just accept a pre-existing `apiClient`.
It was only creating its own to begin with in an attempt to reduce the length of its function
signature and for no other reason.
=> pass apiClient to determineBaseRepo

command/title_body_survey.go
I introduced a regression in my `pr review` work by allowing `GhEditor` to be unskippable in
instances where a body is required (namely, a comment or request changes review). I didn't go back
and explicitly re-allow blank bodies on the title/body helper that issues and prs use.
=> reenable skipping body prompt for pr/issue

.github/workflows/releases.yml, Makefile
Fixes #898
This PR:
- theoretically fixes building our docs site in CI by telling git what author to use when making
commits
- does a small quality of life thing; when cloning the site repo, `gh` is used if it is available.
this is mainly for me locally when I'd rather not have an https url used. it should have no
effect in CI.
=> fix and tweak for site build

command/pr.go, command/pr_test.go, test/fixtures/prViewPreviewWithReviewersByNumber.json
Now handling the "DISMISSED" and "PENDING" states.
I have no evidence that "PENDING" can be returned from API in this context, but it's listed among the possible states in GitHub API docs, so better be safe than sorry. Reviewers with "PENDING" states are omitted from display.
Fixes #934, followup to #762 /cc @doi-t
=> Avoid crash in `pr view` with reviewers

.github/workflows/lint.yml
It turns out that YAML anchors are not supported https://github.com/cli/cli/actions/runs/115915028
Followup to https://github.com/cli/cli/pull/988
=> Fix linter in CI

Makefile
the `site` target is still used in CI and gh hangs the build waiting for authentication
=> do not yet try and use gh from makefile bc of CI

command/pr.go
Just spotted this! Changed `Make a pull request as ready for review` -> `Mark a pull request as ready for review`
=> Fix typo in `pr ready` help

.github/PULL_REQUEST_TEMPLATE/bug_fix.md, README.md, wix.json
=> Rename "master" to "trunk" in various links

cmd/gh/main.go, command/alias.go, command/alias_test.go, command/root.go, internal/config/alias_config.go, internal/config/config_type.go
This PR adds `gh alias set`.
- allows creating aliases, including ones with placeholder arguments (e.g. `$1`)
- validates that you can't set an alias for a non-existent command
- adds a new top level `aliases` section to our config which is created on first use of `alias set`
- allow for composition of commands (see #941 )
- allow for deleting, listing, importing, nor exporting of aliases (see #936)
I did two things I'm nervous about in this PR.
0. modified `main.go` to initialize a `Context`, check the config, and rewrite `argv` if an alias is found.
1. disabled flag parsing for `alias set`. I encountered what I think is a bug where cobra would treat flags inside of single quoted strings as something it should parse (eg `alias set il 'issue list --label="bug"'`). Disabling flag …
=> gh alias set

command/issue.go, command/issue_test.go, command/pr_create.go
=> Query Params in Web mode of Issue/PR creation

command/repo.go, command/repo_test.go
Resolves: #860 
Enable the shorthand of cloning private repository by omitting username.
=> shorthand of clone without username

api/queries_issue.go, api/queries_issue_test.go, command/issue.go, command/issue_test.go
This commit introduces two new flags in order to filter issues per `mentioned` and `milestone`.
See #641
=> Add filters issues
