README.md

Since we're still early, we want to get more feedback to make sure we're taking into account our users' needs and common problems they run into as we continue to build GitHub CLI.

Add feedback to README

---

.goreleaser.yml

Setup fish completion when installing with Homebrew

---

command/root.go
pkg/surveyext/editor.go

fix: Fix typos

---

README.md
source.md

Added build-from-source to the README installation section.

ADD installation from source section to README.

---

README.md

Fix link to docs on README.md

---

README.md

Adds a note to the README for installing from AUR

doc: add arch install instructions

---

pkg/surveyext/editor.go

For context, see https://github.com/cli/cli/issues/308#issuecomment-583444787

Check for $GIT_EDITOR first

---

.gitignore

Ran into these while I was working on #337

Add .vscode and .DS_Store to .gitignore

---

.github/PULL_REQUEST_TEMPLATE/bug_fix.md

adds a basic pull request template for bug fix pull requests
(also includes a comment inline to remind contributors to read the contributing guidelines)
___
[pull request templates reference](https://help.github.com/en/github/building-a-strong-community/about-issue-and-pull-request-templates#pull-request-templates)

Add Bugfix Pull Request Template

---

README.md

To include installing/upgrading from Chocolatey

(doc) Update Windows installation options

---

source.md

[DOCs] Indicate Go's Version Required for Installing from Source

---

.github/CONTRIBUTING.md

(Docs) Updating CONTRIBUTING.md

---

.github/workflows/go.yml

https://help.github.com/en/actions/reference/events-that-trigger-workflows#pull-request-event-pull_request

Enable CI for pull requests from forks

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/submit-a-request.md

This automatically assigns "bug" to bug reports and "enhancement" to feature requests.

Add labels to issue template

---

.goreleaser.yml

Release for arm64 linux

---

command/pr_create.go
command/pr_create_test.go

Fixes #319, closes #460
Also fixes #320

Respect overriden base branch in `pr create --web`

---

command/completion.go

Make sure to handle errors when generating completions

---

command/pr_create.go

Followup to https://github.com/cli/cli/pull/483
Fixes #522

Respect title & body from arguments to `pr create -w`

---

command/issue.go
command/issue_test.go
command/pr.go
command/root.go

Preserve explicit title & body in `issue create --web`

---

command/pr_create.go
git/git.go

Fixes https://github.com/cli/cli/issues/353

Show `git push` output during `pr create`

---

api/queries_pr.go

I don't think using goto here is necessary.

Use break label instead of goto

---

command/root.go

Fix typo in 'overridden'

---

Makefile
cmd/gen-docs/main.go

The old code was outdated after the move to `cli.github.com` docs repo

Fix `make site-docs`

---

.github/workflows/go.yml

https://golang.org/doc/articles/race_detector.html
https://blog.golang.org/race-detector

tests: adding the Go data race detector.

---

api/queries_pr.go
command/pr_test.go
test/fixtures/prListWithDuplicates.json

Fixes https://github.com/cli/cli/issues/592

Remove duplicated PRs from GitHub API response.

---

README.md
docs/gh-vs-hub.md

Fixes #312 
This is intended to provide more official documentation about the difference between gh and hub, and how people should think about them or choose between them. We know it's not going to answer every question, but hopefully it provides a bit more clarity.

Add documentation about gh vs. hub

---

command/pr.go
command/pr_test.go
test/fixtures/prStatusChecks.json
test/fixtures/prStatusClosedMerged.json

Hey! I tried to follow conventions for adding tests, but let me know if you need anything changed!
Closes #613

Show state instead of checks/reviews for closed/merged PRs

---

command/issue.go

`gh issue view` command does not take a branch as an argument.

Fix 'gh issue view' usage description

---

command/pr_create.go
command/pr_create_test.go

Extends #648 with my fixes
Fixes #649

Check for existing pull request on `pr create`

---

command/pr_create.go

Check if PR is already created

---

go.mod
go.sum

This fixes #647 by not retrieving the terminal's background color on init.

Bump glamour dependency

---

command/issue.go
command/issue_test.go
command/pr.go
command/pr_test.go

closes #555
Switches issue, pr view to print to the terminal by default and take `--web`/`-w` to open issue/pr
in browser.

switch {pr,issue} view default

---

command/pr.go
command/pr_test.go

Closes #215 
This adds some unicode icons to PR status! 
Getting the tests to pass made for some good use case testing! 😆

Add unicode to pr status

---

command/repo.go
command/repo_test.go

This adds an "upstream" remote for the parent repository in addition to the "origin" remote. During an in-repo `repo fork` operation, an existing "origin" remote that previously pointed to the parent repo will now be renamed to "upstream" for consistency.
Fixes https://github.com/cli/cli/issues/582
Followup items:
- Decide whether and how to extend this behavior to the fork scenario in `pr create` as well.

Add "upstream" remote after `repo fork`

---

api/queries_issue_test.go
api/queries_repo_test.go
auth/oauth.go
command/issue.go
command/issue_test.go
command/pr_checkout_test.go
command/pr_create_test.go
command/pr_test.go
command/repo_test.go
command/root.go
command/root_test.go
command/testing.go
context/config_setup.go
git/git_test.go
git/ssh_config.go
pkg/githubtemplate/github_template_test.go
pkg/surveyext/editor.go
pkg/text/truncate.go
test/helpers.go
update/update.go
utils/table_printer.go

https://github.com/cli/cli/pull/734

Code fixes informed by golangci-lint failures

---

go.mod
go.sum
utils/utils.go

- Use `spinner.WithWriter` to avoid race condition when initializing spinner https://github.com/briandowns/spinner/pull/90
- Update spinner to avoid race condition after calling `Stop()` https://github.com/briandowns/spinner/pull/92
https://github.com/cli/cli/runs/574650654?check_suite_focus=true

Avoid race conditions when interacting with the spinner

---

command/issue.go
command/issue_test.go
command/pr.go
command/pr_test.go
test/fixtures/issueView_previewWithMetadata.json
test/fixtures/prViewPreviewWithMetadataByNumber.json

I added tests, but let me know if you want a separate test case for that.
@doi-t I hope it's okay I jumped on this one!
Closes #818

Show "Awaiting triage" for empty project state

---

command/repo.go
command/repo_test.go
utils/utils.go

this is not graceful but it will theoretically un-flake our tests

totally inelegant approach to hopefully stopping flakey tests

---

api/queries_issue.go
command/issue.go
command/issue_test.go

This adds `gh issue reopen <issue number or url>`
It looks like this...
Closes second of four features in https://github.com/cli/cli/issues/413

Add `gh issue reopen <issue number or url>`

---

api/queries_pr.go
command/pr.go
command/pr_test.go

This adds `gh pr close` it looks like this 👇
Closes third of four features in #413

Add `gh pr close <numberOrURL>`

---

command/issue.go
command/pr.go

This makes it consistent with other subcommands under `issue/pr`.
Followup to #857, #854, #853, #843
Ref. #862

Tweak syntax in `issue/pr close` docs

---

command/pr_review.go
command/pr_review_test.go
command/root.go

- make credits an :egg:
- unregister review for now

hide stuff

---

command/pr_review.go
command/pr_review_test.go
command/root.go
command/title_body_survey.go
pkg/surveyext/editor.go

This PR adds "light" interactive reviewing; ie still a top-level review but with prompts for review type and adding a body via your editor.
Fixes #434

light interactive pr review

---

command/config.go
command/issue.go

- Some short descriptions start with lowercase. Align the first letter to uppercase.
- Some short descriptions end with period. Align with no period at the end.
```console
$ git rev-parse HEAD
d1bdb31558698541f7e1790cc1a94f187da2585f
$ git grep Short:
command/completion.go:  Short: "Generate shell completion scripts",
command/config.go:      Short: "Set and get gh settings",
command/config.go:      Short: "Prints the value of a given configuration key.",
command/config.go:      Short: "Updates configuration with the value of a given key.",
command/credits.go:     Short: "View project's credits",
command/issue.go:       Short: "Create and view issues",
command/issue.go:       Short: "Create a new issue",
command/issue.go:       Short: "List and filter issues in this repository", …
```

Cosmetic about short descriptions

---

api/queries_pr.go
command/pr.go
command/pr_test.go

This adds `gh pr ready`. It looks like this
_updated screenshot with @billygriffin's text changes_
Closes https://github.com/cli/cli/issues/740
/cc @ampinsk let me know if you need any design changes

Add `gh pr ready`

---

.github/workflows/lint.yml

Overlooked in #734
Ref. https://github.com/cli/cli/pull/978

Enable linting for pull requests

---

docs/releasing.md

This adds some more step to the release documentation. Mainly it encourages a pre-release before the production release because our setup is still a little buggy.

Update release doc content

---

command/alias.go
command/alias_test.go
internal/config/alias_config.go

gh alias list
